version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: google-cloud-discovery_engine
      - dependency-name: google-cloud-discovery_engine-*
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: ruby
