# .rubocop.yml
inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

# We often want to test duck-typed interfaces rather than specific classes, especially in the
# context of the Google API client, which returns dynamic objects that RSpec's `instance_double`
# can't verify.
RSpec/VerifiedDoubles:
  Enabled: false

# This app does not use ActiveRecord, so prevent Rubocop from messing with method names that look
# like ActiveRecord methods (for example, insisting on adding `!` when calling methods called
# `create`).
Rails/SaveBang:
  Enabled: false
# **************************************************************
# TRY NOT TO ADD OVERRIDES IN THIS FILE
#
# This repo is configured to follow the RuboCop GOV.UK styleguide.
# Any rules you override here will cause this repo to diverge from
# the way we write code in all other GOV.UK repos.
#
# See https://github.com/alphagov/rubocop-govuk/blob/main/CONTRIBUTING.md
# **************************************************************
